/* this file is automatically generated - do not edit */

#include "mquickjs_priv.h"

static const uint64_t __attribute((aligned(64))) js_complex_module_table[] = {
  /* atom_table */
  (JS_MTAG_STRING << 1) | (1 << JS_MTAG_BITS) | (1 << (JS_MTAG_BITS + 1)) | (0 << (JS_MTAG_BITS + 2)) | (4 << (JS_MTAG_BITS + 3)), /* "null" (offset=0) */
  0x000000006c6c756e,
  (JS_MTAG_STRING << 1) | (1 << JS_MTAG_BITS) | (1 << (JS_MTAG_BITS + 1)) | (0 << (JS_MTAG_BITS + 2)) | (9 << (JS_MTAG_BITS + 3)), /* "undefined" (offset=2) */
  0x656e696665646e75,
  0x0000000000000064,
  (JS_MTAG_STRING << 1) | (1 << JS_MTAG_BITS) | (1 << (JS_MTAG_BITS + 1)) | (0 << (JS_MTAG_BITS + 2)) | (4 << (JS_MTAG_BITS + 3)), /* "true" (offset=5) */
  0x0000000065757274,
  (JS_MTAG_STRING << 1) | (1 << JS_MTAG_BITS) | (1 << (JS_MTAG_BITS + 1)) | (0 << (JS_MTAG_BITS + 2)) | (5 << (JS_MTAG_BITS + 3)), /* "false" (offset=7) */
  0x00000065736c6166,
  (JS_MTAG_STRING << 1) | (1 << JS_MTAG_BITS) | (1 << (JS_MTAG_BITS + 1)) | (0 << (JS_MTAG_BITS + 2)) | (10 << (JS_MTAG_BITS + 3)), /* "globalThis" (offset=9) */
  0x68546c61626f6c67,
  0x0000000000007369,
  (JS_MTAG_STRING << 1) | (1 << JS_MTAG_BITS) | (1 << (JS_MTAG_BITS + 1)) | (0 << (JS_MTAG_BITS + 2)) | (14 << (JS_MTAG_BITS + 3)), /* "complex_module" (offset=12) */
  0x5f78656c706d6f63,
  0x0000656c75646f6d,
  (JS_MTAG_STRING << 1) | (1 << JS_MTAG_BITS) | (1 << (JS_MTAG_BITS + 1)) | (0 << (JS_MTAG_BITS + 2)) | (7 << (JS_MTAG_BITS + 3)), /* "Complex" (offset=15) */
  0x0078656c706d6f43,
  (JS_MTAG_STRING << 1) | (1 << JS_MTAG_BITS) | (1 << (JS_MTAG_BITS + 1)) | (0 << (JS_MTAG_BITS + 2)) | (6 << (JS_MTAG_BITS + 3)), /* "module" (offset=17) */
  0x0000656c75646f6d,
  (JS_MTAG_STRING << 1) | (1 << JS_MTAG_BITS) | (1 << (JS_MTAG_BITS + 1)) | (0 << (JS_MTAG_BITS + 2)) | (7 << (JS_MTAG_BITS + 3)), /* "example" (offset=19) */
  0x00656c706d617865,
  (JS_MTAG_STRING << 1) | (1 << JS_MTAG_BITS) | (1 << (JS_MTAG_BITS + 1)) | (0 << (JS_MTAG_BITS + 2)) | (8 << (JS_MTAG_BITS + 3)), /* "function" (offset=21) */
  0x6e6f6974636e7566,
  0x0000000000000000,
  (JS_MTAG_STRING << 1) | (1 << JS_MTAG_BITS) | (1 << (JS_MTAG_BITS + 1)) | (0 << (JS_MTAG_BITS + 2)) | (9 << (JS_MTAG_BITS + 3)), /* "fibonacci" (offset=24) */
  0x6363616e6f626966,
  0x0000000000000069,
  (JS_MTAG_STRING << 1) | (1 << JS_MTAG_BITS) | (1 << (JS_MTAG_BITS + 1)) | (0 << (JS_MTAG_BITS + 2)) | (1 << (JS_MTAG_BITS + 3)), /* "n" (offset=27) */
  0x000000000000006e,
  (JS_MTAG_STRING << 1) | (1 << JS_MTAG_BITS) | (1 << (JS_MTAG_BITS + 1)) | (0 << (JS_MTAG_BITS + 2)) | (2 << (JS_MTAG_BITS + 3)), /* "if" (offset=29) */
  0x0000000000006669,
  (JS_MTAG_STRING << 1) | (1 << JS_MTAG_BITS) | (1 << (JS_MTAG_BITS + 1)) | (0 << (JS_MTAG_BITS + 2)) | (6 << (JS_MTAG_BITS + 3)), /* "return" (offset=31) */
  0x00006e7275746572,
  (JS_MTAG_STRING << 1) | (1 << JS_MTAG_BITS) | (1 << (JS_MTAG_BITS + 1)) | (0 << (JS_MTAG_BITS + 2)) | (9 << (JS_MTAG_BITS + 3)), /* "factorial" (offset=33) */
  0x6169726f74636166,
  0x000000000000006c,
  (JS_MTAG_STRING << 1) | (1 << JS_MTAG_BITS) | (1 << (JS_MTAG_BITS + 1)) | (0 << (JS_MTAG_BITS + 2)) | (3 << (JS_MTAG_BITS + 3)), /* "var" (offset=36) */
  0x0000000000726176,
  (JS_MTAG_STRING << 1) | (1 << JS_MTAG_BITS) | (1 << (JS_MTAG_BITS + 1)) | (0 << (JS_MTAG_BITS + 2)) | (10 << (JS_MTAG_BITS + 3)), /* "MathModule" (offset=38) */
  0x75646f4d6874614d,
  0x000000000000656c,
  (JS_MTAG_STRING << 1) | (1 << JS_MTAG_BITS) | (1 << (JS_MTAG_BITS + 1)) | (0 << (JS_MTAG_BITS + 2)) | (3 << (JS_MTAG_BITS + 3)), /* "fib" (offset=41) */
  0x0000000000626966,
  (JS_MTAG_STRING << 1) | (1 << JS_MTAG_BITS) | (1 << (JS_MTAG_BITS + 1)) | (0 << (JS_MTAG_BITS + 2)) | (4 << (JS_MTAG_BITS + 3)), /* "fact" (offset=43) */
  0x0000000074636166,
  (JS_MTAG_STRING << 1) | (1 << JS_MTAG_BITS) | (1 << (JS_MTAG_BITS + 1)) | (0 << (JS_MTAG_BITS + 2)) | (4 << (JS_MTAG_BITS + 3)), /* "name" (offset=45) */
  0x00000000656d616e,
  (JS_MTAG_STRING << 1) | (1 << JS_MTAG_BITS) | (1 << (JS_MTAG_BITS + 1)) | (0 << (JS_MTAG_BITS + 2)) | (7 << (JS_MTAG_BITS + 3)), /* "Module'" (offset=47) */
  0x0027656c75646f4d,
  (JS_MTAG_STRING << 1) | (1 << JS_MTAG_BITS) | (1 << (JS_MTAG_BITS + 1)) | (0 << (JS_MTAG_BITS + 2)) | (7 << (JS_MTAG_BITS + 3)), /* "version" (offset=49) */
  0x006e6f6973726576,

  /* sorted atom table (offset=51) */
  JS_VALUE_ARRAY_HEADER(22),
  JS_ROM_VALUE(15), /* Complex */
  JS_ROM_VALUE(38), /* MathModule */
  JS_ROM_VALUE(47), /* Module' */
  JS_ROM_VALUE(12), /* complex_module */
  JS_ROM_VALUE(19), /* example */
  JS_ROM_VALUE(43), /* fact */
  JS_ROM_VALUE(33), /* factorial */
  JS_ROM_VALUE(7), /* false */
  JS_ROM_VALUE(41), /* fib */
  JS_ROM_VALUE(24), /* fibonacci */
  JS_ROM_VALUE(21), /* function */
  JS_ROM_VALUE(9), /* globalThis */
  JS_ROM_VALUE(29), /* if */
  JS_ROM_VALUE(17), /* module */
  JS_ROM_VALUE(27), /* n */
  JS_ROM_VALUE(45), /* name */
  JS_ROM_VALUE(0), /* null */
  JS_ROM_VALUE(31), /* return */
  JS_ROM_VALUE(5), /* true */
  JS_ROM_VALUE(2), /* undefined */
  JS_ROM_VALUE(36), /* var */
  JS_ROM_VALUE(49), /* version */

};

const JSSTDLibraryDef js_complex_module = {
  js_complex_module_table,
  NULL,  // User modules typically don't define new C functions
  NULL,  // No custom finalizers
  74,    // table length
  64,    // alignment
  51,    // sorted atoms offset
  74,    // global object offset
  0,     // class count
};

